# Portone 백엔드 민감한 정보 관리 (비밀번호, 토큰 등)
apiVersion: v1
kind: Secret
metadata:
  name: portone-secrets             # 시크릿 이름
  namespace: portone-subscription   # 네임스페이스
type: Opaque                       # 일반적인 시크릿 타입
data:
  RDS_PASSWORD: "cGFzc3dvcmQ="      # RDS 데이터베이스 비밀번호 (Base64 인코딩된 "password")
  #COGNITO_CLIENT_SECRET: ""        # Cognito 클라이언트 시크릿 (필요시 활성화) 