# Portone 백엔드 서비스 설정 (외부 접근용)
apiVersion: v1
kind: Service
metadata:
  name: portone-backend-service        # 서비스 이름
  namespace: portone-subscription      # 네임스페이스
  labels:
    app: portone-backend               # 애플리케이션 라벨
spec:
  selector:                            # 어떤 Pod에 연결할지 선택
    app: portone-backend               # portone-backend 라벨을 가진 Pod 선택
  ports:                               # 포트 설정
  - protocol: TCP                      # TCP 프로토콜 사용
    port: 80                           # 외부에서 접근할 포트 (HTTP)
    targetPort: 8000                   # Pod 내부 포트 (FastAPI 포트)
  type: ClusterIP                      # 클러스터 내부 통신용 (ALB Ingress가 외부 접근 처리) 