# Portone 백엔드 자동 스케일링 설정 (HPA)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: portone-backend-hpa        # HPA 이름
  namespace: portone-subscription  # 네임스페이스
spec:
  scaleTargetRef:                   # 스케일링 대상 설정
    apiVersion: apps/v1
    kind: Deployment               # Deployment 타입
    name: portone-backend          # 대상 Deployment 이름
  minReplicas: 1                   # 최소 Pod 개수
  maxReplicas: 5                   # 최대 Pod 개수
  metrics:                         # 스케일링 기준 메트릭
  - type: Resource                 # 리소스 사용량 기반
    resource:
      name: cpu                    # CPU 사용량 기준
      target:
        type: Utilization          # 사용률 기준
        averageUtilization: 70     # CPU 70% 사용 시 스케일 아웃
  - type: Resource                 # 리소스 사용량 기반
    resource:
      name: memory                 # 메모리 사용량 기준
      target:
        type: Utilization          # 사용률 기준
        averageUtilization: 85     # 메모리 85% 사용 시 스케일 아웃 (더 효율적인 리소스 활용) 