# SMS Sender Worker 민감한 정보 관리 (SQS 큐, SMS API 키 등)
apiVersion: v1
kind: Secret
metadata:
  name: sms-sender-secret         # 시크릿 이름
  namespace: sms-sender-worker    # 네임스페이스
type: Opaque                     # 일반적인 시크릿 타입
stringData:                      # 문자열 데이터 (Base64 인코딩 자동 처리)
  SQS_QUEUE_URL: "https://sqs.ap-northeast-2.amazonaws.com/889986388555/SmsSendQueue"  # SQS 메시지 큐 URL
  SOLAPI_SECRET_NAME: "solapi/api-keys"  # AWS Secrets Manager에 저장된 Solapi API 키 참조명
  AWS_REGION: "ap-northeast-2"    # AWS 리전 (서울) 