apiVersion: v1
kind: Secret
metadata:
  name: sms-sender-secret
  namespace: default
type: Opaque
stringData:
  SQS_QUEUE_URL: "https://sqs.ap-northeast-2.amazonaws.com/889986388555/SmsSendQueue"
  SOLAPI_SECRET_NAME: "solapi/api-keys"
  AWS_REGION: "ap-northeast-2" 